permalink: /:year:month:day/:title
url: "https://fodninetyfive.github.io/" #Your url here
baseurl: ""

# variables
name: "C Drive"
description: files in folders
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true